apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    component: frontend
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
        component: frontend
    spec:
      containers:
      - name: frontend
        image: icclabcna/ccp2-k8s-todo-frontend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
        env:
        - name: API_ENDPOINT_URL
          value: http://10.100.118.191:8081